variable "vsphere_underlay" {}
variable "avi" {}
variable "avi_old_password" {}
variable "avi_password" {}
variable "nsx_password" {}
variable "external_gw" {}
variable "transport_zone" {}
variable "vsphere_nested" {}
variable "vsphere_nested_password" {}
variable "nsx_alb_se_cl" {}
