variable "vsphere_nested" {}
variable "external_gw" {}
variable "vsphere_underlay" {}
variable "vsphere_nested_password" {}
variable "ubuntu_ova_path" {}
variable "app" {}
variable "ubuntu_password" {}
variable "app_segments" {}
variable "app_cidr" {}
variable "app_ips" {}
variable "app_segments_vpc" {}
variable "folders_vpc" {}
variable "docker_registry_username" {}
variable "docker_registry_password" {}
