variable "vsphere_underlay" {}
variable "vsphere_nested" {}
variable "external_gw" {}
variable "vcenter_iso_path" {}
variable "iso_location" {}
variable "bios" {}
variable "guest_id" {}
variable "keyboard_type" {}
variable "wait_for_guest_net_timeout" {}
variable "nested_hv_enabled" {}
variable "networks" {}
variable "nested_esxi_root_password" {}
variable "vsphere_underlay_username" {}
variable "vsphere_underlay_password" {}
variable "vsphere_nested_password" {}
variable "date_index" {}
variable "deployment" {}
