variable "vsphere_underlay" {}
variable "vsphere_underlay_username" {}
variable "vsphere_underlay_password" {}
variable "avi" {}
variable "vsphere_nested" {}
variable "vsphere_nested_password" {}
variable "external_gw" {}
variable "avi_port_group" {}
variable "avi_ova_path" {}
variable "nsx_alb_se_cl" {}
variable "date_index" {}