- hosts: localhost
  tasks:

    - name: Migrate vmk1 (VMotion) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vsphere_nested.vcsa_name }}.{{ external_gw.bind.domain}}"
        username: "administrator@{{ vsphere_nested.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vsphere_nested_password') }}"
        validate_certs: false
        esxi_hostname: "{{ vsphere_nested.esxi.basename }}{{ my_idx + 1 }}.{{ external_gw.bind.domain }}"
        device: 'vmk1'
        current_switch_name: 'vSwitch1'
        current_portgroup_name: 'VMotion Network'
        migrate_switch_name: "{{ networks.vsphere.VMotion.vds_name }}"
        migrate_portgroup_name: "{{ networks.vsphere.VMotion.port_group_name }}"
      loop: "{{ vsphere_underlay.networks.vsphere.management.esxi_ips }}"
      loop_control:
        index_var: my_idx

    - name: Migrate vmk2 (VSAN) to the VDS
      community.vmware.vmware_migrate_vmk:
        hostname: "{{ vsphere_nested.vcsa_name }}.{{ external_gw.bind.domain}}"
        username: "administrator@{{ vsphere_nested.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vsphere_nested_password') }}"
        validate_certs: false
        esxi_hostname: "{{ vsphere_nested.esxi.basename }}{{ my_idx + 1 }}.{{ external_gw.bind.domain }}"
        device: 'vmk2'
        current_switch_name: 'vSwitch2'
        current_portgroup_name: 'VSAN Network'
        migrate_switch_name: "{{ networks.vsphere.VSAN.vds_name }}"
        migrate_portgroup_name: "{{ networks.vsphere.VSAN.port_group_name }}"
      loop: "{{ vsphere_underlay.networks.vsphere.management.esxi_ips }}"
      loop_control:
        index_var: my_idx

    - name: Add Management vmkernel port using static network type for vmk3
      community.vmware.vmware_vmkernel:
        hostname: "{{ vsphere_nested.vcsa_name }}.{{ external_gw.bind.domain}}"
        username: "administrator@{{ vsphere_nested.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vsphere_nested_password') }}"
        validate_certs: false
        device: vmk3
        esxi_hostname: "{{ vsphere_nested.esxi.basename }}{{ my_idx + 1 }}.{{ external_gw.bind.domain }}"
        dvswitch_name: "{{ networks.vsphere.management.vds_name }}"
        portgroup_name: "{{ networks.vsphere.management.port_group_name }}-vmk"
        network:
          type: 'static'
          ip_address: "{{ item.1 }}"
          subnet_mask: "{{ vsphere_underlay.networks.vsphere.management.netmask }}"
        state: present
        enable_mgmt: True
      loop: "{{ vsphere_underlay.networks.vsphere.management.esxi_ips | zip(vsphere_underlay.networks.vsphere.management.esxi_ips_temp) | list }}"
      loop_control:
        index_var: my_idx

    - name: Add Management vmkernel port using static network type for vmk4
      community.vmware.vmware_vmkernel:
        hostname: "{{ vsphere_nested.vcsa_name }}.{{ external_gw.bind.domain}}"
        username: "administrator@{{ vsphere_nested.sso.domain_name }}"
        password: "{{ lookup('env', 'TF_VAR_vsphere_nested_password') }}"
        validate_certs: false
        device: vmk4
        esxi_hostname: "{{ vsphere_nested.esxi.basename }}{{ my_idx + 1 }}.{{ external_gw.bind.domain }}"
        dvswitch_name: "{{ networks.vsphere.management.vds_name }}"
        portgroup_name: "{{ networks.vsphere.management.port_group_name }}-vmk"
        network:
          type: 'dhcp'
        state: present
        enable_mgmt: True
      loop: "{{ vsphere_underlay.networks.vsphere.management.esxi_ips }}"
      loop_control:
        index_var: my_idx